version: "3.8"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: petstore
      MYSQL_HOST: 127.0.0.1
    ports:
      - '3306:3306'
    volumes:
      - "db:/var/lib/mysql"

  pet-server:
    build:
      context: .
    depends_on:
      - mysql
    ports:
      - '4000:3000'
    environment:
      DB_HOST: mysql
    volumes: 
      - ./src:/opt/pet-server/src

volumes:
  db:
