/* Generated by restful-react */

export const SPEC_VERSION = "1.0"; 
export interface CreateUserDto {
  username: string;
  password: string;
  email?: string;
  phone?: string;
  status?: number;
  avatar?: string;
}

export interface UserData {
  username: string;
  email: string;
  phone: string;
  avatar: string;
}

export interface LoginDto {
  username: string;
  password: string;
}


export interface UserControllerFindMePathParams {
  username: string
}




export interface CategoryControllerFindAllResponse {[key: string]: any}


export interface PetControllerGetPetByIdResponse {[key: string]: any}

export interface PetControllerGetPetByIdPathParams {
  petId: number
}


export interface PetControllerGetByFiltersResponse {[key: string]: any}

export interface PetControllerGetByFiltersQueryParams {
  category: number;
  status: string;
}

