/* Generated by restful-react */

export const SPEC_VERSION = "1.0"; 
export interface FailedResponseDto {
  /**
   * http code (error)
   */
  statusCode: number;
  data: {
  error?: string;
};
  message: string;
  /**
   * when failed, the code field will be 1
   */
  code: number;
  url: string;
}

export interface CreateUserDto {
  username: string;
  password: string;
  email?: string;
  phone?: string;
  status?: number;
  avatar?: string;
}

export interface UserData {
  /**
   * Name of the user
   */
  username: string;
  /**
   * Email of the user
   */
  email: string;
  /**
   * Phone number of the user
   */
  phone: string;
  /**
   * Avatar of the user
   */
  avatar: string;
}

export interface LoginDto {
  username: string;
  password: string;
}

export interface LoginResult {
  token: string;
}

export interface SuccessResponseDto {
  data: {[key: string]: any};
  /**
   * when success, the code field will be 0
   */
  code: number;
  message: string;
}


export interface UserControllerFindMePathParams {
  username: string
}




export interface CategoryControllerFindAllResponse {[key: string]: any}


export interface PetControllerGetPetByIdResponse {[key: string]: any}

export interface PetControllerGetPetByIdPathParams {
  petId: number
}


export interface PetControllerGetByFiltersResponse {[key: string]: any}

export interface PetControllerGetByFiltersQueryParams {
  category: number;
  status: string;
}

